version: 2.1

executors:
  default:
    working_directory: ~/repo/
    docker:
      - image: circleci/node:10-stretch

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: sudo npm -g install npm@6
      - restore_cache:
          key: v1-node10-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-node10-{{ checksum "package-lock.json" }}
          paths:
            - ~/node_modules/
      - run: npm run build -- --prod --stats-json
      - store_artifacts:
          path: dist/my-ngrx8-app/stats-es2015.json
          destination: stats.json

workflow:
  test-build:
    jobs:
      - build
